development:
  adapter: postgresql
  database: yobs_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: yobs_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: Yobs
  pool: 5
  timeout: 5000